FROM python:3.8
# set work directory
WORKDIR ./
# copy project
COPY ./ /.
ADD ./Minrec.jpg ./Minrec.jpg
# install dependencies
RUN pip install telebot
RUN pip install psycopg2
RUN pip install validate_email
# run app
CMD ["python", "main.py"]
